name: foodieexpress
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.2.2
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  objectbox_generator: ^4.0.2

dependency_overrides:
  analyzer: 8.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
